name: 'setup-nuxmv'
description: 'setup nuXMV on your Github workflow'
author: 'Alexander Weigl'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
#inputs:
#  platform:
#    description: Your input description here
#    required: true
#    default: '1000'

# Define your outputs here.
#outputs:
#  time:
#    description: Your output description here

runs:
  using: node20
  main: dist/index.js
